//
//  AppDelegate.m
//  ezrainstagram
//
//  Created by Ezra Bekele on 7/9/18.
//  Copyright © 2018 ezrainstagram. All rights reserved.
//

#import "AppDelegate.h"
#import "Parse/Parse.h"
#import "LoginViewController.h"

@interface AppDelegate ()

@end

@implementation AppDelegate


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    ParseClientConfiguration * config =  [ParseClientConfiguration configurationWithBlock: ^ (id < ParseMutableClientConfiguration > _Nonnull configuration) {
        configuration.applicationId = @"ezraAppID";
        configuration.clientKey = @"ezraMasterKey";
        configuration.server = @"https://ezra-insta.herokuapp.com/parse";
    }];
    
     [Parse initializeWithConfiguration:config];
    
    [self listenForLogoutNotification];
    [self skipLoginScreenIfLoggedIn];
    
   
    
    return YES;
}

-(void)setupParse {
    
    // Initialize Parse
    // Set applicationId and server based on the values in the Heroku settings.
    // clientKey is not used on Parse open source unless explicitly configured
    
    [Parse initializeWithConfiguration: [ParseClientConfiguration configurationWithBlock: ^ (id < ParseMutableClientConfiguration > _Nonnull configuration) {
        
//        // UPDATE APP ID, CLIENT ID, AND SERVER URL HERE
//        configuration.applicationId = @"ezraAppID";
//        configuration.clientKey = @"ezraMasterKey";
//        configuration.server = @"https://ezra-insta.herokuapp.com/parse";
//        configuration.localDatastoreEnabled = NO;
        
        // If not correct, will get error message: "The data couldn’t be read because it isn’t in the correct format."  (Had trouble using a custom name, so use their autogenerated app name, not a url that you may have entered.  If you did enter something unique, then just change it back.
    }]];
    
    
}

-(void)skipLoginScreenIfLoggedIn {
    
    if ([PFUser currentUser]) {
        
        UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
        
        self.window.rootViewController = [storyboard instantiateViewControllerWithIdentifier:@"mainPics"];
        
    
        
//        [self setRootViewControllerHavingStoryBoardIdentifier:@"mainPics"];  // Overriding Storyboard settings.
    }
}

-(void)listenForLogoutNotification {
    [[NSNotificationCenter defaultCenter] addObserverForName:@"didLogout" object:nil queue:[NSOperationQueue mainQueue] usingBlock:^(NSNotification * _Nonnull note) {
        
        [self logOutCurrentUser];
    }];
}

-(void)logOutCurrentUser {
    [PFUser logOutInBackgroundWithBlock:^(NSError * _Nullable error) {
        if (error != nil) {
            NSLog(@"%@", error.localizedDescription);
        } else {
            [self setRootViewControllerHavingStoryBoardIdentifier:@"LoginViewController"];
        }
    }];
}

-(void)setRootViewControllerHavingStoryBoardIdentifier: (NSString *)identifier {
    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
    LoginViewController *loginViewController = [storyboard instantiateViewControllerWithIdentifier:@"LoginViewController"];
    self.window.rootViewController = loginViewController;
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
}




@end
